# Local Development/Testing Configuration
version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api/
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - '3000:3000'
    env_file:
      - server/.env
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:5173
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
