# docker-compose.prod.yml

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - frontend
      - server

  frontend:
    image: ghcr.io/agrireceipts/base-1-frontend:latest
    expose:
      - '80'
    restart: unless-stopped
    depends_on:
      - server

  server:
    image: ghcr.io/agrireceipts/base-1-server:latest
    restart: unless-stopped
    # This is the key line, just like your local setup
    env_file:
      - server/.env.production
    environment:
      - FRONTEND_URL=https://www.agri-receipts.in
      - NODE_ENV=production # Also important for security settings
      - SESSION_SECRET=${SESSION_SECRET} # Make sure to set this in your .env file!
    expose:
      - '3000'
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - '6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  caddy_data:
  caddy_config:
